spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: testuser
    password: testpass
    driver-class-name: org.postgresql.Driver
  h2.console:
    enabled: true
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto:  update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug



